<?php

/**
 * Implementation of hook_theme().
 */
function deonline_formatters_theme() {
  return array(
    'deonline_formatters_formatter_list' => array(
      'arguments' => array('element' => NULL),
    ),
  );
}

/**
 * Implementation of hook_field_formatter_info().
 */
function deonline_formatters_field_formatter_info() {
  return array(
    'list' => array(
      'label' => t('Item list'),
      'field types' => array('text'),
      'multiple values' => CONTENT_HANDLE_MODULE,
    ),
  );
}

function theme_deonline_formatters_formatter_list($items) {
  $temp = array();
  foreach($items as $key => $value) {
    if (is_numeric($key)) {
      $temp[] = ($allowed =_text_allowed_values($items)) ? $allowed : $value['#item']['safe'];
    }
  }
  return theme('item_list', $temp);
}
//marina-list-arrow-green